### ISSUE TITLE
setQrcodeVersion设置为1,2,3,4时报错

### ISSUE THREAD

**Issue by chushiyun2016** [lizhangqu/qrcode#1]
当设置setQrcodeVersion为某些值时（1,2,3,4），会报错：
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 64
    at com.swetake.util.Qrcode.divideDataBy8Bits(Qrcode.java:545)
    at com.swetake.util.Qrcode.calQrcode(Qrcode.java:438)

**Comment by ddknight** [comment]
你引用QRcode.jar,请注明出处:http://www.swetake.com/qrcode/
